[book]
authors = ["Maksim Ryndin"]
language = "en"
multilingual = false
src = "src"
title = "Distributed systems for a busy engineer"

[build]
create-missing = false

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maksimryndin/distributed-book"
site-url = "https://maksimryndin.github.io/distributed-book/"