[book]
authors = ["Maksim Ryndin"]
language = "en"
multilingual = false
src = "src"
title = "Distributed systems for busy engineer"


[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maksimryndin/distributed-book"
site-url = "https://maksimryndin.github.io/distributed-book/"