name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_and_maybe_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build
        run: mdbook build

      - name: Test
        run: mdbook test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
        # Only deploy on a push to master, not on a pull request.
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'maksimryndin/distributed-book'